const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

test("desktop shell is configured with isolation and Codex app-server", () => {
  const main = fs.readFileSync(path.join(__dirname, "main.cjs"), "utf8");
  const threadProfile = fs.readFileSync(path.join(__dirname, "ai-thread-profile.cjs"), "utf8");
  const preload = fs.readFileSync(path.join(__dirname, "preload.cjs"), "utf8");
  assert.match(main, /app-server/);
  assert.match(main, /notify\("initialized"\)/);
  assert.match(main, /thread\/resume/);
  assert.match(main, /turn\/interrupt", \{ threadId: activeTurnThreadId, turnId \}/);
  assert.match(main, /model\/list/);
  assert.match(main, /account\/rateLimits\/read/);
  assert.match(main, /account\/usage\/read/);
  assert.match(main, /effort: effort \|\| null/);
  assert.match(main, /serviceTier: serviceTier \|\| null/);
  assert.match(main, /buildEphemeralThreadStartParams/);
  assert.match(threadProfile, /ephemeral: true/);
  assert.match(main, /method: "5e\/performance"/);
  assert.match(main, /threadId: plan\.ephemeralRender \? null : requestThreadId/);
  assert.match(main, /Promise\.allSettled\(safeAttachments\.map/);
  assert.match(main, /fs\.promises\.unlink\(result\.value\.file\)/);
  assert.equal((main.match(/rpc\("turn\/start"/g) || []).length, 1, "backend must not retry a turn implicitly");
  assert.match(main, /imageGeneration/);
  assert.match(main, /contextIsolation: true/);
  assert.match(main, /FIVE_E_DEV_USER_DATA/);
  assert.match(main, /FIVE_E_DISABLE_GPU/);
  assert.match(main, /nodeIntegration: false/);
  assert.match(main, /Menu\.setApplicationMenu\(null\)/);
  assert.match(main, /win\.setMenu\(null\)/);
  assert.match(main, /win\.setMenuBarVisibility\(false\)/);
  assert.match(main, /splash\.html/);
  assert.match(main, /show: false/);
  assert.match(main, /ready-to-show/);
  assert.match(main, /titleBarStyle: "hidden"/);
  assert.match(main, /titleBarOverlay/);
  assert.ok(fs.existsSync(path.join(__dirname, "splash.html")));
  assert.match(preload, /contextBridge\.exposeInMainWorld/);
  assert.match(preload, /codex:models/);
  assert.match(preload, /codex:account/);
  assert.match(preload, /desktop-shell/);
  assert.match(preload, /capture:sources/);
  assert.match(preload, /local-images:pick-folder/);
  assert.match(preload, /local-images:list/);
  assert.match(main, /desktopCapturer\.getSources/);
  assert.match(main, /LOCAL_IMAGE_EXTENSIONS/);
});

test("image prompt includes the no-label drawing rule", () => {
  const prompt = fs.readFileSync(path.join(__dirname, "..", "js", "ai-prompt.js"), "utf8");
  assert.match(prompt, /문자, 숫자, 단위, 수식, 기호, 라벨, 로고, 워터마크, 지시선과 화살표/);
  assert.match(prompt, /buildDiscussionPrompt/);
  assert.match(prompt, /imagegen 이미지 생성 도구를 정확히 1회 호출한다/);
  assert.doesNotMatch(prompt, /docs\//);
});

test("AI panel auto-connects, shows progress, and filters image-generation events", () => {
  const panel = fs.readFileSync(path.join(__dirname, "..", "js", "ai-panel.js"), "utf8");
  const events = fs.readFileSync(path.join(__dirname, "..", "js", "ai-events.js"), "utf8");
  const markup = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
  const styles = fs.readFileSync(path.join(__dirname, "..", "css", "ai-panel.css"), "utf8");
  const examLibrary = fs.readFileSync(path.join(__dirname, "..", "js", "exam-library.js"), "utf8");
  const imageLibrary = fs.readFileSync(path.join(__dirname, "..", "js", "parts-library.js"), "utf8");
  assert.match(panel, /5e\.aiConversationId/);
  assert.match(panel, /fiveEDesktop\.start\(\)/);
  assert.match(panel, /fiveEDesktop\.models\(\)/);
  assert.match(panel, /model: modelSelect\.value/);
  assert.match(panel, /effort: effortSelect\.value/);
  assert.match(panel, /serviceTier: speedSelect\.value/);
  assert.match(panel, /loadAccountOverview/);
  assert.match(panel, /addTokenFooter/);
  assert.match(panel, /영역 코멘트/);
  assert.match(panel, /미리보기 축소/);
  assert.match(panel, /미리보기 확대/);
  assert.match(panel, /수정 요청 영역 지정/);
  assert.match(panel, /pointerdown/);
  assert.match(panel, /openComparison/);
  assert.match(panel, /attachments\.push/);
  assert.match(panel, /캔버스로 출력/);
  assert.match(panel, /이미지가 완성되었습니다/);
  assert.doesNotMatch(examLibrary, /prompt:\s*"이 기출문제 이미지를 참고하여/);
  assert.doesNotMatch(imageLibrary, /prompt:\s*"이 참고 이미지의 핵심 구조와 비율은 유지하고/);
  assert.match(examLibrary, /references:\s*items\.map/);
  assert.match(imageLibrary, /selectedIds\.map/);
  assert.match(examLibrary, /5e:library-closed/);
  assert.match(imageLibrary, /5e:library-closed/);
  assert.match(panel, /setGenerating\(true/);
  assert.match(panel, /parseAiEvent/);
  assert.match(events, /item\?\.type === "imageGeneration"/);
  assert.match(events, /item\?\.type === "agentMessage"/);
  assert.match(events, /item\.phase === "commentary"/);
  assert.match(events, /imageDataUrl/);
  assert.match(events, /thread\/tokenUsage\/updated/);
  assert.match(markup, /data-ai-reference-search/);
  assert.match(markup, /이미지 검색…/);
  assert.match(markup, /화면 캡처/);
  assert.match(markup, /이미지 불러오기/);
  assert.match(markup, /작업 취소/);
  assert.match(markup, /data-ai-chat-send/);
  assert.match(markup, /data-ai-mode="diagram"/);
  assert.match(markup, />그림형<\/button>/);
  assert.match(markup, /v1\.5\.3 · 2026\.08\.11/);
  assert.doesNotMatch(markup, /업데이트 2026\.08\.09/);
  assert.match(panel, /openCaptureCrop/);
  assert.match(panel, /references = \[\]/);
  assert.match(panel, /createAiReferenceSearch/);
  assert.match(panel, /클립보드 이미지/);
  assert.match(markup, /data-ai-speed/);
  assert.match(markup, /기출문제 라이브러리/);
  assert.match(markup, /data-ai-compare/);
  assert.match(markup, /data-ai-capture/);
  assert.match(markup, /파일 탐색기/);
  assert.match(markup, /multiple/);
  assert.ok(
    markup.indexOf('data-ai-previews') < markup.indexOf('class="ai-reference-section"'),
    "generated results must stay above the collapsible reference images",
  );
  assert.match(styles, /grid-template-areas: "results conversation"/);
  assert.match(styles, /\.ai-status\[data-kind="ok"\].*var\(--accent/);
});
